package com.niteshsynergy.entity;

import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@Builder
@AllArgsConstructor
@Document(collection = "internal_customer_payments")
public class InternalCustomerPayments {
    @Id
    private String id; // Auto-generated by MongoDB

    @NotBlank(message = "Parent ID is required")
    private String parentId; // Links to `InternalCustomers.id`

    @NotBlank(message = "Trace ID is required")
    private String traceId; // Links to `InternalCustomers.id`

    @NotBlank(message = "Transaction ID is required")
    private String transactionId;

    @NotBlank(message = "Order ID is required")
    private String orderId;

    @NotBlank(message = "Payment mode is required")
    private String paymentMode; // Online / Cash

    @NotBlank(message = "Payment gateway is required")
    private String paymentGateway; // RazorPay, PhonePe, HDFC, etc.

    @NotBlank(message = "Payment status is required")
    private String paymentStatus; // success, failed, refund

    @NotNull(message = "Amount is required")
    @PositiveOrZero(message = "Amount cannot be negative")
    private Double amount;

    @NotNull(message = "Created On is required")
    private LocalDateTime createdOn;

    @NotNull(message = "Updated On is required")
    private LocalDateTime updatedOn;
}
